services:
  roleta_backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: roleta-backend
    restart: always
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "3010:3000"
    networks:
      - rede_dpg_global

  roleta_frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3010
    container_name: roleta-frontend
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - roleta_backend
    networks:
      - rede_dpg_global  

networks:
  rede_dpg_global:
    driver: bridge